### PR TITLE
tick timers: don't ignore general graardor

### PR DESCRIPTION
**Pull request by CJP10**

### CODE REVIEW

**Comment by CJP10** [comment]
@xKylee looks good now

**Comment by dedruss-ops** [comment]
Noticed that the plugin reads graardor as being a ranged attack.

**Comment by CJP10** [comment]
@dedruss-ops it should only render as a range attack when you are not tanking.

**Comment by dedruss-ops** [comment]
> @dedruss-ops it should only render as a range attack when you are not tanking. If that's broken let me know.

It must be broken. Currently I'm soloing the boss and the only person in the room.

**Comment by CJP10** [comment]
> > @dedruss-ops it should only render as a range attack when you are not tanking. If that's broken let me know.
> 
> It must be broken. Currently I'm soloing the boss and the only person in the room.

Can you take a short video? If not might have to wait a bit until i get a chance to make it over to bandos.

**Comment by dedruss-ops** [comment]
Yeah I can do that. Do you have a discord? I'm not sure how to attach it on here. Otherwise you can message me. My name is zach#3181

**Pull request merged**
