### PR TITLE
cerberus: Merge into external plugins repo

### PR DESCRIPTION
**Pull request by Im2be**
Merging cerberus from OpenOSRS into this repo

### CODE REVIEW

**Comment by xKylee** [comment]
Can you sort checkstyle, the extra padding needs removing

**Comment by xKylee** [comment]
Also remove extra whitespace

**Comment by xKylee** [comment]
And add back { and } which were removed.

**Comment by Im2be** [comment]
Gonna add one more bugfix before PR'ing again

**Pull request merged**
